# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FastSPGM_CV_FDR <- function(x, D_0, D_1, kfold = NA_real_, nlambda = NA_real_, step_size = NA_real_, intercept = TRUE, global = FALSE, regularization = NULL, alpha = NULL, N = NA_real_, delta_upper = NA_real_, true_graph = NULL) {
    .Call(`_ModPGMInference_FastSPGM_CV_FDR`, x, D_0, D_1, kfold, nlambda, step_size, intercept, global, regularization, alpha, N, delta_upper, true_graph)
}

FastSPGM_EBIC_FDR <- function(x, D_0, D_1, gamma = NA_real_, nlambda = NA_real_, step_size = NA_real_, intercept = TRUE, global = FALSE, regularization = NULL, alpha = NULL, N = NA_real_, delta_upper = NA_real_, true_graph = NULL) {
    .Call(`_ModPGMInference_FastSPGM_EBIC_FDR`, x, D_0, D_1, gamma, nlambda, step_size, intercept, global, regularization, alpha, N, delta_upper, true_graph)
}

FastSqrtPGM_CV_FDR <- function(x, kfold = NA_real_, nlambda = NA_real_, step_size = NA_real_, intercept = TRUE, global = FALSE, regularization = NULL, alpha = NULL, N = NA_real_, delta_upper = NA_real_, true_graph = NULL) {
    .Call(`_ModPGMInference_FastSqrtPGM_CV_FDR`, x, kfold, nlambda, step_size, intercept, global, regularization, alpha, N, delta_upper, true_graph)
}

FastSqrtPGM_EBIC_FDR <- function(x, gamma = NA_real_, nlambda = NA_real_, step_size = NA_real_, intercept = TRUE, global = FALSE, regularization = NULL, alpha = NULL, N = NA_real_, delta_upper = NA_real_, true_graph = NULL) {
    .Call(`_ModPGMInference_FastSqrtPGM_EBIC_FDR`, x, gamma, nlambda, step_size, intercept, global, regularization, alpha, N, delta_upper, true_graph)
}

FastTPGM_CV_FDR <- function(x, D, kfold = NA_real_, nlambda = NA_real_, step_size = NA_real_, intercept = TRUE, global = FALSE, alpha = NULL, regularization = NULL, N = NA_real_, delta_upper = NA_real_, true_graph = NULL) {
    .Call(`_ModPGMInference_FastTPGM_CV_FDR`, x, D, kfold, nlambda, step_size, intercept, global, alpha, regularization, N, delta_upper, true_graph)
}

FastTPGM_EBIC_FDR <- function(x, D, gamma = NA_real_, nlambda = NA_real_, step_size = NA_real_, intercept = TRUE, global = FALSE, alpha = NULL, regularization = NULL, N = NA_real_, delta_upper = NA_real_, true_graph = NULL) {
    .Call(`_ModPGMInference_FastTPGM_EBIC_FDR`, x, D, gamma, nlambda, step_size, intercept, global, alpha, regularization, N, delta_upper, true_graph)
}

Gibbs_SPGM <- function(psi, theta, D_0, D_1, nSample, burn_in = NULL, thin = NULL) {
    .Call(`_ModPGMInference_Gibbs_SPGM`, psi, theta, D_0, D_1, nSample, burn_in, thin)
}

Gibbs_SqrtPGM <- function(psi, theta, nSample, burn_in = NULL, thin = NULL) {
    .Call(`_ModPGMInference_Gibbs_SqrtPGM`, psi, theta, nSample, burn_in, thin)
}

Gibbs_TPGM <- function(psi, theta, D, nSample, burn_in = NULL, thin = NULL) {
    .Call(`_ModPGMInference_Gibbs_TPGM`, psi, theta, D, nSample, burn_in, thin)
}

true_sd_SPGM <- function(x, psi, theta, D_0, D_1) {
    .Call(`_ModPGMInference_true_sd_SPGM`, x, psi, theta, D_0, D_1)
}

true_sd_SqrtPGM <- function(x, psi, theta) {
    .Call(`_ModPGMInference_true_sd_SqrtPGM`, x, psi, theta)
}

true_sd_TPGM <- function(x, psi, theta, D) {
    .Call(`_ModPGMInference_true_sd_TPGM`, x, psi, theta, D)
}

